name: CI/CD
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        env:
          CI: true
        run: npm run test:unit
      - name: Build
        env:
          BASE: /interest-calculator/
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
